<?xml version="1.0" encoding="UTF-8"?>
<testng-results failed="1" passed="3" skipped="0" total="4">
<suite name="Cucumber" duration-ms="37">
<test name="Cucumber" duration-ms="37">
<class name="Retry">
<test-method name="Test cases that pass aren't retried" status="PASS" duration-ms="3" started-at="1970-01-01T00:00:00.001Z" finished-at="1970-01-01T00:00:00.004Z"/>
<test-method name="Test cases that fail are retried if within the --retry limit" status="PASS" duration-ms="3" started-at="1970-01-01T00:00:00.009Z" finished-at="1970-01-01T00:00:00.012Z"/>
<test-method name="Test cases that fail will continue to retry up to the --retry limit" status="PASS" duration-ms="3" started-at="1970-01-01T00:00:00.021Z" finished-at="1970-01-01T00:00:00.024Z"/>
<test-method name="Test cases won't retry after failing more than the --retry limit" status="FAIL" duration-ms="3" started-at="1970-01-01T00:00:00.033Z" finished-at="1970-01-01T00:00:00.036Z">
<exception class="Error">
<message><![CDATA[
Given a step that always fails..............................................failed
]]></message>
<full-stacktrace>
<![CDATA[Error: Exception in step
samples/retry/retry.feature:18]]>
</full-stacktrace>
</exception>
</test-method>
</class>
</test>
</suite>
</testng-results>
